### PR TITLE
Custom Dialer for NTS

### PR DESCRIPTION
**Pull request by lambchr**
This PR is to solve my issue describe in https://github.com/beevik/nts/issues/3

### CODE REVIEW

**Comment by beevik** [comment]
Thanks for the pull request.  Before I comment, I'd like to better understand your use case.  Could you provide a sample of the code that uses your proposed API changes?

**Comment by lambchr** [comment]
> Thanks for the pull request. Before I comment, I'd like to better understand your use case. Could you provide a sample of the code that uses your proposed API changes?

Thanks for taking a look @beevik! Here is a small sample of how we will use the proposed API changes:

```
const (
	hostNTP = "ntp-server"
	portNTP = 123
	hostProxy = "proxy-server"
	portProxy = 4321
)

func NTSDialer(localAddress, remoteAddress string) (*tls.Conn, error) {
	// use the hostProxy and portProxy to dial to the proxy and establish a connection
	// send network and address of NTP server to proxy, it will need this to establish the next connection
	// perform a TLS handshake with the connection made to the proxy and return this connection once established
}

sessionOpts := &nts.SessionOptions{
	Dialer: ProxyDialer,
	NTPAddr: net.JoinHostPort(hostNTP, strconv.Itoa(portNTP)),
}
session, err := nts.NewSessionWithOptions(hostNTP, sessionOpts)
if err != nil {
	panic(err) // not how errors are actually handled
}

func NTPDialer(localAddress, remoteAddress string) (net.Conn, error) {
	// use the hostProxy and portProxy to dial to the proxy and establish a connection
	// send network and address of NTP server to proxy, it will need this to establish the next connection
}

queryOpts := &ntp.QueryOptions{
	Dialer:  NTPDialer,
}
response, err := session.QueryWithOptions(queryOpts)
```

Let me know if you need anything else to review!

**Comment by beevik** [comment]
After examining your proposal, I'd like to propose some modifications that should make the API more similar in style and approach to existing overrides (in the ntp and nts packages).

Could you please take a look at https://github.com/beevik/nts/pull/5 and see if my proposal would work for your use case?

**Comment by lambchr** [comment]
> After examining your proposal, I'd like to propose some modifications that should make the API more similar in style and approach to existing overrides (in the ntp and nts packages).
> 
> Could you please take a look at #5 and see if my proposal would work for your use case?

Yeah that proposal will also work for us @beevik , I added a couple of nits (one would make things easier for our custom dialer). Thanks again for taking a look

**Comment by beevik** [comment]
Closing this pull request since all work has moved to https://github.com/beevik/nts/pull/5

**Pull request closed without merging**
